% Clear vars
clc;
clear;

% Read the image
bananaImage = imread("./images/bruised4.jpg");
% Display
figure();
imshow(bananaImage), title('Good Banana Image jpg');

% Get the banana mask from Thresholder App
[BW_banana, maskedRGB] = createMask(bananaImage);
% Clean up the mask
BW_banana = bwareaopen(BW_banana, 500);
BW_banana = imfill(BW_banana, 'holes');
% Keep only the largest region (the banana)
BW_banana = bwareafilt(BW_banana, 1);
% Display
figure();
subplot(1,2,1), imshow(maskedRGB), title('Masked Banana');
subplot(1,2,2), imshow(BW_banana), title('Banana Mask');

% Detect the bounding box of the banana
props = regionprops(BW_banana, 'BoundingBox');
bbox = props(1).BoundingBox

% Crop the the RGB and mask images
croppedRGB = imcrop(bananaImage, bbox);
croppedMask = imcrop(BW_banana, bbox);

% Convert to HSV
croppedHSV = rgb2hsv(croppedRGB);

% Pull the HSV channels
H = croppedHSV(:,:,1);
S = croppedHSV(:,:,2);
V = croppedHSV(:,:,3);

% Set threshold for how dark a bruise is
darkThresh = 0.6;
% Set a saturation threshold
satMin = 0.3;

% Approximate a yellow hue span
yellowLow  = 0.10;
yellowHigh = 0.18;

% Detect "good" yellow pixels
goodYellow = (H >= yellowLow) & (H <= yellowHigh) & (S > 0.4) & (V > 0.5);

% Create a bruise mask out of non-good pixels
bruiseMask = croppedMask & (V < darkThresh) & (S > satMin) & ~goodYellow;

% Display
figure;
imshow(bruiseMask), title('Bruise Mask (Cropped)');

% Find the counts of yellow pixels and bruise pixels
N_banana = nnz(croppedMask);
N_bruise = nnz(bruiseMask);
bruiseRatio = N_bruise / N_banana;

% Make a decision
if bruiseRatio > 0.3
    disp('The banana is bruised.');
else
    disp('The banana is not bruised.');
end

% Display
overlay = croppedRGB;
overlay(repmat(bruiseMask,[1 1 3])) = 255;
figure; imshow(overlay); title('Detected Bruises (Cleaned & Cropped)');

% Display Final Image
figure();
subplot(2,3,1), imshow(bananaImage), title('Bruised Banana Image jpg');
subplot(2,3,2), imshow(maskedRGB), title('Masked Banana');
subplot(2,3,3), imshow(BW_banana), title('Banana Mask');
subplot(2,3,4), imshow(bruiseMask), title('Bruise Mask (Cropped)'); 
overlay = croppedRGB;
overlay(repmat(bruiseMask,[1 1 3])) = 255;
subplot(2,3,5), imshow(overlay); title('Detected Bruises (Cleaned & Cropped)');

% === FUNCTIONS ===

function [BW,maskedRGBImage] = createMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 28-Nov-2025
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.000;
channel1Max = 1.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.487;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
